# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: postSchema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10postSchema.proto\x12\nredditPost\"\xbc\x02\n\x08PostList\x12(\n\x05posts\x18\x01 \x03(\x0b\x32\x19.redditPost.PostList.Post\x1a\x85\x02\n\x04Post\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tsubreddit\x18\x02 \x01(\t\x12\x17\n\x0f\x61uthor_fullname\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x1f\n\x17subreddit_name_prefixed\x18\x05 \x01(\t\x12\x0b\n\x03ups\x18\x06 \x01(\x05\x12\x11\n\tthumbnail\x18\x07 \x01(\t\x12\x0f\n\x07\x63reated\x18\x08 \x01(\x02\x12\x14\n\x0csubreddit_id\x18\t \x01(\t\x12\n\n\x02id\x18\n \x01(\t\x12\x0b\n\x03url\x18\x0b \x01(\t\x12\x14\n\x0cnum_comments\x18\x0c \x01(\x05\x12\x1d\n\x15total_awards_received\x18\r \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'postSchema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSTLIST._serialized_start=33
  _POSTLIST._serialized_end=349
  _POSTLIST_POST._serialized_start=88
  _POSTLIST_POST._serialized_end=349
# @@protoc_insertion_point(module_scope)
